// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { AppInformation, WebUIConfiguration } from "../types/application";
import type { ClientConfig, RequestOptions } from "../client";
import { fromWire, sdkRequest } from "../client";

/**
 * Returns basic runtime information, message totals and latest release version.
 */
export async function appInformation(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<AppInformation> {
  const _resp = await sdkRequest<AppInformation>({
    method: "GET",
    path: `/api/v1/info`,
    operationId: "appInformation",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "AppInformation") as AppInformation;
}

/**
 * Returns configuration settings for the web UI. Intended for web UI only!
 */
export async function webUiConfigurationResponse(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<WebUIConfiguration> {
  const _resp = await sdkRequest<WebUIConfiguration>({
    method: "GET",
    path: `/api/v1/webui`,
    operationId: "webUiConfigurationResponse",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "WebUIConfiguration") as WebUIConfiguration;
}

export class ApplicationNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Returns basic runtime information, message totals and latest release version.
   */
  appInformation(requestOptions?: RequestOptions): ReturnType<typeof appInformation> {
    return appInformation(this._config, requestOptions);
  }
  /**
   * Returns configuration settings for the web UI. Intended for web UI only!
   */
  webUiConfigurationResponse(
    requestOptions?: RequestOptions,
  ): ReturnType<typeof webUiConfigurationResponse> {
    return webUiConfigurationResponse(this._config, requestOptions);
  }
}
