// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { MessagesSummary } from "../types/messages";
import type { ClientConfig, RequestOptions } from "../client";
import { fromWire, queryValue, sdkRequest } from "../client";

export interface GetMessagesParamsParams {
  start?: number;
  limit?: number;
}

/**
 * Returns messages from the mailbox ordered from newest to oldest.
 *
 * @param start - Pagination offset
 * @param limit - Limit number of results
 */
export async function getMessagesParams(
  config: ClientConfig,
  { start, limit }: GetMessagesParamsParams = {},
  requestOptions?: RequestOptions,
): Promise<MessagesSummary> {
  const _resp = await sdkRequest<MessagesSummary>({
    method: "GET",
    path: `/api/v1/messages`,
    operationId: "getMessagesParams",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      start: queryValue(start, "form", true),
      limit: queryValue(limit, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "MessagesSummary") as MessagesSummary;
}

export interface SetReadStatusParamsParams {
  tz?: string;
  ids?: string[];
  read?: boolean;
  search?: string;
}

/**
 * You can optionally provide an array of IDs or a search string. If neither IDs nor search is provided then all mailbox messages are updated.
 *
 * @param tz - Optional [timezone
 *   identifier](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) used
 *   only for `before:` & `after:` searches (eg: "Pacific/Auckland").
 * @param ids - Optional array of message database IDs
 * @param read - Read status
 * @param search - Optional messages matching a search
 */
export async function setReadStatusParams(
  config: ClientConfig,
  { tz, ids, read, search }: SetReadStatusParamsParams = {},
  requestOptions?: RequestOptions,
): Promise<string> {
  const _resp = await sdkRequest<string>({
    method: "PUT",
    path: `/api/v1/messages`,
    operationId: "setReadStatusParams",
    responseDecoder: "text",
    ...requestOptions,
    query: {
      tz: queryValue(tz, "form", true),
    },
    body: {
      IDs: ids,
      Read: read,
      Search: search,
    },
    config,
  });
  return _resp.data;
}

export interface DeleteMessagesParamsParams {
  ids?: string[];
}

/**
 * Delete individual or all messages. If no IDs are provided then all messages are deleted.
 *
 * @param ids - Array of message database IDs
 */
export async function deleteMessagesParams(
  config: ClientConfig,
  { ids }: DeleteMessagesParamsParams = {},
  requestOptions?: RequestOptions,
): Promise<string> {
  const _resp = await sdkRequest<string>({
    method: "DELETE",
    path: `/api/v1/messages`,
    operationId: "deleteMessagesParams",
    responseDecoder: "text",
    ...requestOptions,
    body: {
      IDs: ids,
    },
    config,
  });
  return _resp.data;
}

export interface SearchParamsParams {
  query: string;
  start?: string;
  limit?: string;
  tz?: string;
}

/**
 * Returns messages matching [a search](https://mailpit.axllent.org/docs/usage/search-filters/), sorted by received date (descending).
 *
 * @param query - Search query
 * @param start - Pagination offset
 * @param limit - Limit results
 * @param tz - Optional [timezone
 *   identifier](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) used
 *   only for `before:` & `after:` searches (eg: "Pacific/Auckland").
 */
export async function searchParams(
  config: ClientConfig,
  { query, start, limit, tz }: SearchParamsParams,
  requestOptions?: RequestOptions,
): Promise<MessagesSummary> {
  const _resp = await sdkRequest<MessagesSummary>({
    method: "GET",
    path: `/api/v1/search`,
    operationId: "searchParams",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      query: queryValue(query, "form", true),
      start: queryValue(start, "form", true),
      limit: queryValue(limit, "form", true),
      tz: queryValue(tz, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "MessagesSummary") as MessagesSummary;
}

export interface DeleteSearchParamsParams {
  query: string;
  tz?: string;
}

/**
 * Delete all messages matching [a search](https://mailpit.axllent.org/docs/usage/search-filters/).
 *
 * @param query - Search query
 * @param tz - [Timezone
 *   identifier](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) used
 *   only for `before:` & `after:` searches (eg: "Pacific/Auckland").
 */
export async function deleteSearchParams(
  config: ClientConfig,
  { query, tz }: DeleteSearchParamsParams,
  requestOptions?: RequestOptions,
): Promise<string> {
  const _resp = await sdkRequest<string>({
    method: "DELETE",
    path: `/api/v1/search`,
    operationId: "deleteSearchParams",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      query: queryValue(query, "form", true),
      tz: queryValue(tz, "form", true),
    },
    config,
  });
  return _resp.data;
}

export class MessagesNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Returns messages from the mailbox ordered from newest to oldest.
   */
  getParams(
    params: GetMessagesParamsParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getMessagesParams> {
    return getMessagesParams(this._config, params, requestOptions);
  }
  /**
   * You can optionally provide an array of IDs or a search string. If neither IDs nor search is provided then all mailbox messages are updated.
   */
  setReadStatusParams(
    params: SetReadStatusParamsParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof setReadStatusParams> {
    return setReadStatusParams(this._config, params, requestOptions);
  }
  /**
   * Delete individual or all messages. If no IDs are provided then all messages are deleted.
   */
  deleteParams(
    params: DeleteMessagesParamsParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteMessagesParams> {
    return deleteMessagesParams(this._config, params, requestOptions);
  }
  /**
   * Returns messages matching [a search](https://mailpit.axllent.org/docs/usage/search-filters/), sorted by received date (descending).
   */
  searchParams(
    params: SearchParamsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof searchParams> {
    return searchParams(this._config, params, requestOptions);
  }
  /**
   * Delete all messages matching [a search](https://mailpit.axllent.org/docs/usage/search-filters/).
   */
  deleteSearchParams(
    params: DeleteSearchParamsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteSearchParams> {
    return deleteSearchParams(this._config, params, requestOptions);
  }
}
