// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { Message } from "../types/message";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, fromWire, sdkRequest } from "../client";

export interface GetMessageParamsParams {
  id: string;
}

/**
 * Returns the summary of a message, marking the message as read. The ID can be set to `latest` to return the latest message.
 *
 * @param id - Message database ID or "latest"
 */
export async function getMessageParams(
  config: ClientConfig,
  { id }: GetMessageParamsParams,
  requestOptions?: RequestOptions,
): Promise<Message> {
  const _resp = await sdkRequest<Message>({
    method: "GET",
    path: `/api/v1/message/${encodePathSegment(id)}`,
    operationId: "getMessageParams",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "Message") as Message;
}

export interface GetHeadersParamsParams {
  id: string;
}

/**
 * Returns the message headers as an array. Note that header keys are returned alphabetically. The ID can be set to `latest` to return the latest message headers.
 *
 * @param id - Message database ID or "latest"
 */
export async function getHeadersParams(
  config: ClientConfig,
  { id }: GetHeadersParamsParams,
  requestOptions?: RequestOptions,
): Promise<{ [key: string]: string[] }> {
  const _resp = await sdkRequest<{ [key: string]: string[] }>({
    method: "GET",
    path: `/api/v1/message/${encodePathSegment(id)}/headers`,
    operationId: "getHeadersParams",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface AttachmentParamsParams {
  id: string;
  partId: string;
}

/**
 * This will return the attachment part using the appropriate Content-Type. The ID can be set to `latest` to reference the latest message.
 *
 * @param id - Message database ID or "latest"
 * @param partId - Attachment part ID
 */
export async function attachmentParams(
  config: ClientConfig,
  { id, partId }: AttachmentParamsParams,
  requestOptions?: RequestOptions,
): Promise<Blob | File> {
  const _resp = await sdkRequest<Blob | File>({
    method: "GET",
    path: `/api/v1/message/${encodePathSegment(id)}/part/${encodePathSegment(partId)}`,
    operationId: "attachmentParams",
    responseDecoder: "bytes",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface ThumbnailParamsParams {
  id: string;
  partId: string;
}

/**
 * This will return a cropped 180x120 JPEG thumbnail of an image attachment. If the image is smaller than 180x120 then the image is padded. If the attachment is not an image then a blank image is returned. The ID can be set to `latest` to return the latest message.
 *
 * @param id - Message database ID or "latest"
 * @param partId - Attachment part ID
 */
export async function thumbnailParams(
  config: ClientConfig,
  { id, partId }: ThumbnailParamsParams,
  requestOptions?: RequestOptions,
): Promise<Blob | File> {
  const _resp = await sdkRequest<Blob | File>({
    method: "GET",
    path: `/api/v1/message/${encodePathSegment(id)}/part/${encodePathSegment(partId)}/thumb`,
    operationId: "thumbnailParams",
    responseDecoder: "bytes",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface DownloadRawParamsParams {
  id: string;
}

/**
 * Returns the full email source as plain text. The ID can be set to `latest` to return the latest message source.
 *
 * @param id - Message database ID or "latest"
 */
export async function downloadRawParams(
  config: ClientConfig,
  { id }: DownloadRawParamsParams,
  requestOptions?: RequestOptions,
): Promise<string> {
  const _resp = await sdkRequest<string>({
    method: "GET",
    path: `/api/v1/message/${encodePathSegment(id)}/raw`,
    operationId: "downloadRawParams",
    responseDecoder: "text",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface ReleaseMessageParamsParams {
  id: string;
  to: string[];
}

/**
 * Release a message via a pre-configured external SMTP server. This is only enabled if message relaying has been configured. The ID can be set to `latest` to reference the latest message.
 *
 * @param id - Message database ID
 * @param to - Array of email addresses to relay the message to
 */
export async function releaseMessageParams(
  config: ClientConfig,
  { id, to }: ReleaseMessageParamsParams,
  requestOptions?: RequestOptions,
): Promise<string> {
  const _resp = await sdkRequest<string>({
    method: "POST",
    path: `/api/v1/message/${encodePathSegment(id)}/release`,
    operationId: "releaseMessageParams",
    responseDecoder: "text",
    ...requestOptions,
    body: {
      To: to,
    },
    config,
  });
  return _resp.data;
}

export interface SendMessageParamsParams {
  from: {
    /**
     * Email address
     */
    email: string;
    /**
     * Optional name
     */
    name?: string;
  };
  attachments?: {
    /**
     * Base64-encoded string of the file content
     */
    content: string;
    /**
     * Optional Content-ID (`cid`) for attachment.
     * If this field is set then the file is attached inline.
     */
    contentId?: string;
    /**
     * Optional Content Type for the the attachment.
     * If this field is not set (or empty) then the content type is automatically detected.
     */
    contentType?: string;
    /**
     * Filename
     */
    filename: string;
  }[];
  bcc?: string[];
  cc?: {
    /**
     * Email address
     */
    email: string;
    /**
     * Optional name
     */
    name?: string;
  }[];
  html?: string;
  headers?: { [key: string]: string };
  replyTo?: {
    /**
     * Email address
     */
    email: string;
    /**
     * Optional name
     */
    name?: string;
  }[];
  subject?: string;
  tags?: string[];
  text?: string;
  to?: {
    /**
     * Email address
     */
    email: string;
    /**
     * Optional name
     */
    name?: string;
  }[];
}

/**
 * Sends an email message through the HTTP API with sender, recipient, and message content details. Provide `From` with an `Email` address, and use `Attachments` for files encoded in base64. A 200 response includes the sent message's database ID.
 *
 * Send a message via the HTTP API.
 *
 * @param from - "From" recipient
 * @param attachments - Attachments
 * @param bcc - Bcc recipients email addresses only
 * @param cc - Cc recipients
 * @param html - Message body (HTML)
 * @param headers - Optional headers in {"key":"value"} format
 * @param replyTo - Optional Reply-To recipients
 * @param subject - Subject
 * @param tags - Mailpit tags
 * @param text - Message body (text)
 * @param to - "To" recipients
 */
export async function sendMessageParams(
  config: ClientConfig,
  {
    from,
    attachments,
    bcc,
    cc,
    html,
    headers,
    replyTo,
    subject,
    tags,
    text,
    to,
  }: SendMessageParamsParams,
  requestOptions?: RequestOptions,
): Promise<{
  /**
   * Database ID
   */
  id?: string;
}> {
  const _resp = await sdkRequest<{
    /**
     * Database ID
     */
    id?: string;
  }>({
    method: "POST",
    path: `/api/v1/send`,
    operationId: "sendMessageParams",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      From: from,
      Attachments: attachments,
      Bcc: bcc,
      Cc: cc,
      HTML: html,
      Headers: headers,
      ReplyTo: replyTo,
      Subject: subject,
      Tags: tags,
      Text: text,
      To: to,
    },
    config,
  });
  return _resp.data;
}

export class MessageNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Returns the summary of a message, marking the message as read. The ID can be set to `latest` to return the latest message.
   */
  getParams(
    params: GetMessageParamsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getMessageParams> {
    return getMessageParams(this._config, params, requestOptions);
  }
  /**
   * Returns the message headers as an array. Note that header keys are returned alphabetically. The ID can be set to `latest` to return the latest message headers.
   */
  getHeadersParams(
    params: GetHeadersParamsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getHeadersParams> {
    return getHeadersParams(this._config, params, requestOptions);
  }
  /**
   * This will return the attachment part using the appropriate Content-Type. The ID can be set to `latest` to reference the latest message.
   */
  attachmentParams(
    params: AttachmentParamsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof attachmentParams> {
    return attachmentParams(this._config, params, requestOptions);
  }
  /**
   * This will return a cropped 180x120 JPEG thumbnail of an image attachment. If the image is smaller than 180x120 then the image is padded. If the attachment is not an image then a blank image is returned. The ID can be set to `latest` to return the latest message.
   */
  thumbnailParams(
    params: ThumbnailParamsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof thumbnailParams> {
    return thumbnailParams(this._config, params, requestOptions);
  }
  /**
   * Returns the full email source as plain text. The ID can be set to `latest` to return the latest message source.
   */
  downloadRawParams(
    params: DownloadRawParamsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof downloadRawParams> {
    return downloadRawParams(this._config, params, requestOptions);
  }
  /**
   * Release a message via a pre-configured external SMTP server. This is only enabled if message relaying has been configured. The ID can be set to `latest` to reference the latest message.
   */
  releaseParams(
    params: ReleaseMessageParamsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof releaseMessageParams> {
    return releaseMessageParams(this._config, params, requestOptions);
  }
  /**
   * Sends an email message through the HTTP API with sender, recipient, and message content details. Provide `From` with an `Email` address, and use `Attachments` for files encoded in base64. A 200 response includes the sent message's database ID.
   *
   * Send a message via the HTTP API.
   */
  sendParams(
    params: SendMessageParamsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof sendMessageParams> {
    return sendMessageParams(this._config, params, requestOptions);
  }
}
