// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { HTMLCheckResponse, LinkCheckResponse, SpamAssassinResponse } from "../types/other";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, fromWire, queryValue, sdkRequest } from "../client";

export interface HtmlCheckParamsParams {
  id: string;
}

/**
 * Returns the summary of the message HTML checker. The ID can be set to `latest` to return the latest message.
 *
 * @param id - Message database ID or "latest"
 */
export async function htmlCheckParams(
  config: ClientConfig,
  { id }: HtmlCheckParamsParams,
  requestOptions?: RequestOptions,
): Promise<HTMLCheckResponse> {
  const _resp = await sdkRequest<HTMLCheckResponse>({
    method: "GET",
    path: `/api/v1/message/${encodePathSegment(id)}/html-check`,
    operationId: "htmlCheckParams",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "HTMLCheckResponse") as HTMLCheckResponse;
}

export interface LinkCheckParamsParams {
  id: string;
  follow?: string;
}

/**
 * Returns the summary of the message Link checker. The ID can be set to `latest` to return the latest message.
 *
 * @param id - Message database ID or "latest"
 * @param follow - Follow redirects
 */
export async function linkCheckParams(
  config: ClientConfig,
  { id, follow }: LinkCheckParamsParams,
  requestOptions?: RequestOptions,
): Promise<LinkCheckResponse> {
  const _resp = await sdkRequest<LinkCheckResponse>({
    method: "GET",
    path: `/api/v1/message/${encodePathSegment(id)}/link-check`,
    operationId: "linkCheckParams",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      follow: queryValue(follow, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "LinkCheckResponse") as LinkCheckResponse;
}

export interface SpamAssassinCheckParamsParams {
  id: string;
}

/**
 * Returns the SpamAssassin summary (if enabled) of the message. The ID can be set to `latest` to return the latest message.
 *
 * @param id - Message database ID or "latest"
 */
export async function spamAssassinCheckParams(
  config: ClientConfig,
  { id }: SpamAssassinCheckParamsParams,
  requestOptions?: RequestOptions,
): Promise<SpamAssassinResponse> {
  const _resp = await sdkRequest<SpamAssassinResponse>({
    method: "GET",
    path: `/api/v1/message/${encodePathSegment(id)}/sa-check`,
    operationId: "spamAssassinCheckParams",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "SpamAssassinResponse") as SpamAssassinResponse;
}

export class OtherNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Returns the summary of the message HTML checker. The ID can be set to `latest` to return the latest message.
   */
  htmlCheckParams(
    params: HtmlCheckParamsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof htmlCheckParams> {
    return htmlCheckParams(this._config, params, requestOptions);
  }
  /**
   * Returns the summary of the message Link checker. The ID can be set to `latest` to return the latest message.
   */
  linkCheckParams(
    params: LinkCheckParamsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof linkCheckParams> {
    return linkCheckParams(this._config, params, requestOptions);
  }
  /**
   * Returns the SpamAssassin summary (if enabled) of the message. The ID can be set to `latest` to return the latest message.
   */
  spamAssassinCheckParams(
    params: SpamAssassinCheckParamsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof spamAssassinCheckParams> {
    return spamAssassinCheckParams(this._config, params, requestOptions);
  }
}
