// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, sdkRequest } from "../client";

/**
 * Lists all unique tags currently assigned to messages. Use this endpoint to retrieve the available tag values when you need to inspect message tags.
 *
 * Returns a JSON array of all unique message tags.
 */
export async function getAllTags(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<string[]> {
  const _resp = await sdkRequest<string[]>({
    method: "GET",
    path: `/api/v1/tags`,
    operationId: "getAllTags",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface SetTagsParamsParams {
  ids: string[];
  tags: string[];
}

/**
 * This will overwrite any existing tags for selected message database IDs. To remove all tags from a message, pass an empty tags array.
 *
 * @param ids - Array of message database IDs
 * @param tags - Array of tag names to set
 */
export async function setTagsParams(
  config: ClientConfig,
  { ids, tags }: SetTagsParamsParams,
  requestOptions?: RequestOptions,
): Promise<string> {
  const _resp = await sdkRequest<string>({
    method: "PUT",
    path: `/api/v1/tags`,
    operationId: "setTagsParams",
    responseDecoder: "text",
    ...requestOptions,
    body: {
      IDs: ids,
      Tags: tags,
    },
    config,
  });
  return _resp.data;
}

export interface RenameTagParamsParams {
  tag: string;
  name: string;
}

/**
 * Renames an existing tag. Use `Tag` to identify the tag and provide `Name` as its replacement name. The request body is optional, but when supplied it must include `Name`.
 *
 * Renames an existing tag.
 *
 * @param tag - The url-encoded tag name to rename
 * @param name - New name
 */
export async function renameTagParams(
  config: ClientConfig,
  { tag, name }: RenameTagParamsParams,
  requestOptions?: RequestOptions,
): Promise<string> {
  const _resp = await sdkRequest<string>({
    method: "PUT",
    path: `/api/v1/tags/${encodePathSegment(tag)}`,
    operationId: "renameTagParams",
    responseDecoder: "text",
    ...requestOptions,
    body: {
      Name: name,
    },
    config,
  });
  return _resp.data;
}

export interface DeleteTagParamsParams {
  tag: string;
}

/**
 * Deletes a tag. This will not delete any messages with the tag, but will remove the tag from any messages containing the tag.
 *
 * @param tag - The url-encoded tag name to delete
 */
export async function deleteTagParams(
  config: ClientConfig,
  { tag }: DeleteTagParamsParams,
  requestOptions?: RequestOptions,
): Promise<string> {
  const _resp = await sdkRequest<string>({
    method: "DELETE",
    path: `/api/v1/tags/${encodePathSegment(tag)}`,
    operationId: "deleteTagParams",
    responseDecoder: "text",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class TagsNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists all unique tags currently assigned to messages. Use this endpoint to retrieve the available tag values when you need to inspect message tags.
   *
   * Returns a JSON array of all unique message tags.
   */
  getAll(requestOptions?: RequestOptions): ReturnType<typeof getAllTags> {
    return getAllTags(this._config, requestOptions);
  }
  /**
   * This will overwrite any existing tags for selected message database IDs. To remove all tags from a message, pass an empty tags array.
   */
  setParams(
    params: SetTagsParamsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof setTagsParams> {
    return setTagsParams(this._config, params, requestOptions);
  }
  /**
   * Renames an existing tag. Use `Tag` to identify the tag and provide `Name` as its replacement name. The request body is optional, but when supplied it must include `Name`.
   *
   * Renames an existing tag.
   */
  renameParams(
    params: RenameTagParamsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof renameTagParams> {
    return renameTagParams(this._config, params, requestOptions);
  }
  /**
   * Deletes a tag. This will not delete any messages with the tag, but will remove the tag from any messages containing the tag.
   */
  deleteParams(
    params: DeleteTagParamsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteTagParams> {
    return deleteTagParams(this._config, params, requestOptions);
  }
}
