// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { ChaosTriggers } from "../types/testing";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, fromWire, queryValue, sdkRequest, toWire } from "../client";

/**
 * Returns the current Chaos triggers configuration. This API route will return an error if Chaos is not enabled at runtime.
 */
export async function getChaos(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<ChaosTriggers> {
  const _resp = await sdkRequest<ChaosTriggers>({
    method: "GET",
    path: `/api/v1/chaos`,
    operationId: "getChaos",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "ChaosTriggers") as ChaosTriggers;
}

export type SetChaosParamsParams = ChaosTriggers;

/**
 * Set the Chaos triggers configuration and return the updated values. This API route will return an error if Chaos is not enabled at runtime. If any triggers are omitted from the request, then those are reset to their default values with a 0% probability (ie: disabled). Setting a blank `{}` will reset all triggers to their default values.
 *
 * @param authentication - Trigger for Chaos
 * @param recipient - Trigger for Chaos
 * @param sender - Trigger for Chaos
 */
export async function setChaosParams(
  config: ClientConfig,
  { authentication, recipient, sender }: SetChaosParamsParams = {},
  requestOptions?: RequestOptions,
): Promise<ChaosTriggers> {
  const _resp = await sdkRequest<ChaosTriggers>({
    method: "PUT",
    path: `/api/v1/chaos`,
    operationId: "setChaosParams",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      Authentication: toWire(authentication, "ChaosTrigger"),
      Recipient: toWire(recipient, "ChaosTrigger"),
      Sender: toWire(sender, "ChaosTrigger"),
    },
    config,
  });
  return fromWire(_resp.data, "ChaosTriggers") as ChaosTriggers;
}

export interface GetMessageHtmlParamsParams {
  id: string;
  embed?: string;
}

/**
 * Renders just the message's HTML part which can be used for UI integration testing. Attached inline images are modified to link to the API provided they exist. Note that is the message does not contain a HTML part then an 404 error is returned. The ID can be set to `latest` to return the latest message.
 *
 * @param id - Message database ID or "latest"
 * @param embed - If this is route is to be embedded in an iframe, set embed to
 *   `1` in the URL to add `target="_blank"` and `rel="noreferrer noopener"` to all
 *   links. In addition, a small script will be added to the end of the document to
 *   post (postMessage()) the height of the document back to the parent window for
 *   optional iframe height resizing. Note that this will also *transform* the
 *   message into a full HTML document (if it isn't already), so this option is
 *   useful for viewing but not programmatic testing.
 */
export async function getMessageHtmlParams(
  config: ClientConfig,
  { id, embed }: GetMessageHtmlParamsParams,
  requestOptions?: RequestOptions,
): Promise<string> {
  const _resp = await sdkRequest<string>({
    method: "GET",
    path: `/view/${encodePathSegment(id)}.html`,
    operationId: "getMessageHtmlParams",
    responseDecoder: "text",
    ...requestOptions,
    query: {
      embed: queryValue(embed, "form", true),
    },
    config,
  });
  return _resp.data;
}

export interface GetMessageTextParamsParams {
  id: string;
}

/**
 * Renders just the message's text part which can be used for UI integration testing. The ID can be set to `latest` to return the latest message.
 *
 * @param id - Message database ID or "latest"
 */
export async function getMessageTextParams(
  config: ClientConfig,
  { id }: GetMessageTextParamsParams,
  requestOptions?: RequestOptions,
): Promise<string> {
  const _resp = await sdkRequest<string>({
    method: "GET",
    path: `/view/${encodePathSegment(id)}.txt`,
    operationId: "getMessageTextParams",
    responseDecoder: "text",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class TestingNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Returns the current Chaos triggers configuration. This API route will return an error if Chaos is not enabled at runtime.
   */
  getChaos(requestOptions?: RequestOptions): ReturnType<typeof getChaos> {
    return getChaos(this._config, requestOptions);
  }
  /**
   * Set the Chaos triggers configuration and return the updated values. This API route will return an error if Chaos is not enabled at runtime. If any triggers are omitted from the request, then those are reset to their default values with a 0% probability (ie: disabled). Setting a blank `{}` will reset all triggers to their default values.
   */
  setChaosParams(
    params: SetChaosParamsParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof setChaosParams> {
    return setChaosParams(this._config, params, requestOptions);
  }
  /**
   * Renders just the message's HTML part which can be used for UI integration testing. Attached inline images are modified to link to the API provided they exist. Note that is the message does not contain a HTML part then an 404 error is returned. The ID can be set to `latest` to return the latest message.
   */
  getMessageHtmlParams(
    params: GetMessageHtmlParamsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getMessageHtmlParams> {
    return getMessageHtmlParams(this._config, params, requestOptions);
  }
  /**
   * Renders just the message's text part which can be used for UI integration testing. The ID can be set to `latest` to return the latest message.
   */
  getMessageTextParams(
    params: GetMessageTextParamsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getMessageTextParams> {
    return getMessageTextParams(this._config, params, requestOptions);
  }
}
