// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * AppInformation struct
 */
export interface AppInformation {
  /**
   * Database path
   */
  database?: string;
  /**
   * Database size in bytes
   */
  databaseSize?: number;
  /**
   * Latest Mailpit version
   */
  latestVersion?: string;
  /**
   * Total number of messages in the database
   */
  messages?: number;
  /**
   * Runtime statistics
   */
  runtimeStats?: {
    /**
     * Current memory usage in bytes
     */
    memory?: number;
    /**
     * Database runtime messages deleted
     */
    messagesDeleted?: number;
    /**
     * Accepted runtime SMTP messages
     */
    smtpAccepted?: number;
    /**
     * Total runtime accepted messages size in bytes
     */
    smtpAcceptedSize?: number;
    /**
     * Ignored runtime SMTP messages (when using --ignore-duplicate-ids)
     */
    smtpIgnored?: number;
    /**
     * Rejected runtime SMTP messages
     */
    smtpRejected?: number;
    /**
     * Mailpit server uptime in seconds
     */
    uptime?: number;
  };
  /**
   * Tags and message totals per tag
   */
  tags?: { [key: string]: number };
  /**
   * Total number of messages in the database
   */
  unread?: number;
  /**
   * Current Mailpit version
   */
  version?: string;
}

/**
 * Web UI configuration settings
 */
export interface WebUIConfiguration {
  /**
   * Whether Chaos support is enabled at runtime
   */
  chaosEnabled?: boolean;
  /**
   * Whether messages with duplicate IDs are ignored
   */
  duplicatesIgnored?: boolean;
  /**
   * Whether the delete button should be hidden
   */
  hideDeleteAllButton?: boolean;
  /**
   * Optional label to identify this Mailpit instance
   */
  label?: string;
  /**
   * Message Relay information
   */
  messageRelay?: {
    /**
     * Only allow relaying to these recipients (regex)
     */
    allowedRecipients?: string;
    /**
     * Block relaying to these recipients (regex)
     */
    blockedRecipients?: string;
    /**
     * Whether message relaying (release) is enabled
     */
    enabled?: boolean;
    /**
     * Overrides the "From" address for all relayed messages
     */
    overrideFrom?: string;
    /**
     * Preserve the original Message-IDs when relaying messages
     */
    preserveMessageIds?: boolean;
    /**
     * Enforced Return-Path (if set) for relay bounces
     */
    returnPath?: string;
    /**
     * The configured SMTP server address
     */
    smtpServer?: string;
  };
  /**
   * Whether SpamAssassin is enabled
   */
  spamAssassin?: boolean;
}
