// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { Address } from "./shared";

/**
 * Attachment struct for inline images and attachments
 */
export interface Attachment {
  /**
   * File checksums
   */
  checksums?: {
    /**
     * MD5 checksum hash of file
     */
    md5?: string;
    /**
     * SHA1 checksum hash of file
     */
    sha1?: string;
    /**
     * SHA256 checksum hash of file
     */
    sha256?: string;
  };
  /**
   * Content ID
   */
  contentId?: string;
  /**
   * Content type
   */
  contentType?: string;
  /**
   * File name
   */
  fileName?: string;
  /**
   * Attachment part ID
   */
  partId?: string;
  /**
   * Size in bytes
   */
  size?: number;
}

/**
 * ListUnsubscribe contains a summary of List-Unsubscribe & List-Unsubscribe-Post headers
 * including validation of the link structure
 */
export interface ListUnsubscribe {
  /**
   * Validation errors (if any)
   */
  errors?: string;
  /**
   * List-Unsubscribe header value
   */
  header?: string;
  /**
   * List-Unsubscribe-Post value (if set)
   */
  headerPost?: string;
  /**
   * Detected links, maximum one email and one HTTP(S) link
   */
  links?: string[];
}

/**
 * Message data excluding physical attachments
 */
export interface Message {
  /**
   * Message attachments
   */
  attachments?: Attachment[];
  /**
   * Bcc addresses
   */
  bcc?: Address[];
  /**
   * Cc addresses
   */
  cc?: Address[];
  /**
   * Message RFC3339Nano date & time (if set), else date & time received
   * ([extended RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6) format with optional nano seconds)
   */
  date?: string;
  /**
   * An address such as "Barry Gibbs <bg@example.com>" is represented
   * as Address{Name: "Barry Gibbs", Address: "bg@example.com"}.
   */
  from?: Address;
  /**
   * Message body HTML
   */
  html?: string;
  /**
   * Database ID
   */
  id?: string;
  /**
   * Inline message attachments
   */
  inline?: Attachment[];
  /**
   * ListUnsubscribe contains a summary of List-Unsubscribe & List-Unsubscribe-Post headers
   * including validation of the link structure
   */
  listUnsubscribe?: ListUnsubscribe;
  /**
   * Message ID
   */
  messageId?: string;
  /**
   * ReplyTo addresses
   */
  replyTo?: Address[];
  /**
   * Return-Path
   */
  returnPath?: string;
  /**
   * Message size in bytes
   */
  size?: number;
  /**
   * Message subject
   */
  subject?: string;
  /**
   * Message tags
   */
  tags?: string[];
  /**
   * Message body text
   */
  text?: string;
  /**
   * To addresses
   */
  to?: Address[];
  /**
   * Username used for authentication (if provided) with the SMTP or Send API
   */
  username?: string;
}
