// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { Address } from "./shared";

/**
 * MessagesSummary is a summary of a list of messages
 */
export interface MessagesSummary {
  /**
   * Messages summary
   */
  messages?: MessageSummary[];
  /**
   * Total number of messages matching current query
   */
  messagesCount?: number;
  /**
   * Total number of unread messages matching current query
   */
  messagesUnread?: number;
  /**
   * Pagination offset
   */
  start?: number;
  /**
   * All current tags
   */
  tags?: string[];
  /**
   * Total number of messages in mailbox
   */
  total?: number;
  /**
   * Total number of unread messages in mailbox
   */
  unread?: number;
}

/**
 * MessageSummary struct for frontend messages
 */
export interface MessageSummary {
  /**
   * Whether the message has any attachments
   */
  attachments?: number;
  /**
   * Bcc addresses
   */
  bcc?: Address[];
  /**
   * Cc addresses
   */
  cc?: Address[];
  /**
   * Received RFC3339Nano date & time ([extended RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6) format with optional nano seconds)
   */
  created?: string;
  /**
   * An address such as "Barry Gibbs <bg@example.com>" is represented
   * as Address{Name: "Barry Gibbs", Address: "bg@example.com"}.
   */
  from?: Address;
  /**
   * Database ID
   */
  id?: string;
  /**
   * Message ID
   */
  messageId?: string;
  /**
   * Read status
   */
  read?: boolean;
  /**
   * Reply-To address
   */
  replyTo?: Address[];
  /**
   * Message size in bytes (total)
   */
  size?: number;
  /**
   * Message snippet includes up to 250 characters
   */
  snippet?: string;
  /**
   * Email subject
   */
  subject?: string;
  /**
   * Message tags
   */
  tags?: string[];
  /**
   * To address
   */
  to?: Address[];
  /**
   * Username used for authentication (if provided) with the SMTP or Send API
   */
  username?: string;
}
