// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Response represents the HTML check response struct
 */
export interface HTMLCheckResponse {
  /**
   * All platforms tested, mainly for the web UI
   */
  platforms?: { [key: string]: string[] };
  /**
   * Total weighted result for all scores
   */
  total?: HTMLCheckTotal;
  /**
   * List of warnings from tests
   */
  warnings?: HTMLCheckWarning[];
}

/**
 * Result struct
 */
export interface HTMLCheckResult {
  /**
   * Family eg: Outlook, Mozilla Thunderbird
   */
  family?: string;
  /**
   * Friendly name of result, combining family, platform & version
   */
  name?: string;
  /**
   * Note number for partially supported if applicable
   */
  noteNumber?: string;
  /**
   * Platform eg: ios, android, windows
   */
  platform?: string;
  /**
   * Support [yes, no, partial]
   */
  support?: string;
  /**
   * Family version eg: 4.7.1, 2019-10, 10.3
   */
  version?: string;
}

/**
 * Score struct
 */
export interface HTMLCheckScore {
  /**
   * Number of matches in the document
   */
  found?: number;
  /**
   * Total percentage partially supported
   */
  partial?: number;
  /**
   * Total percentage supported
   */
  supported?: number;
  /**
   * Total percentage unsupported
   */
  unsupported?: number;
}

/**
 * Total weighted result for all scores
 */
export interface HTMLCheckTotal {
  /**
   * Total number of HTML nodes detected in message
   */
  nodes?: number;
  /**
   * Overall percentage partially supported
   */
  partial?: number;
  /**
   * Overall percentage supported
   */
  supported?: number;
  /**
   * Total number of tests done
   */
  tests?: number;
  /**
   * Overall percentage unsupported
   */
  unsupported?: number;
}

/**
 * Warning represents a failed test
 */
export interface HTMLCheckWarning {
  /**
   * Category [css, html]
   */
  category?: string;
  /**
   * Description
   */
  description?: string;
  /**
   * Keywords
   */
  keywords?: string;
  /**
   * Notes based on results
   */
  notesByNumber?: { [key: string]: string };
  /**
   * Test results
   */
  results?: HTMLCheckResult[];
  /**
   * Score struct
   */
  score?: HTMLCheckScore;
  /**
   * Slug identifier
   */
  slug?: string;
  /**
   * Tags
   */
  tags?: string[];
  /**
   * Friendly title
   */
  title?: string;
  /**
   * URL to caniemail.com
   */
  url?: string;
}

/**
 * Link struct
 */
export interface Link {
  /**
   * HTTP status definition
   */
  status?: string;
  /**
   * HTTP status code
   */
  statusCode?: number;
  /**
   * Link URL
   */
  url?: string;
}

/**
 * Response represents the Link check response
 */
export interface LinkCheckResponse {
  /**
   * Total number of errors
   */
  errors?: number;
  /**
   * Tested links
   */
  links?: Link[];
}

/**
 * Rule struct
 */
export interface Rule {
  /**
   * SpamAssassin rule description
   */
  description?: string;
  /**
   * SpamAssassin rule name
   */
  name?: string;
  /**
   * Spam rule score
   */
  score?: number;
}

/**
 * Result is a SpamAssassin result
 */
export interface SpamAssassinResponse {
  /**
   * If populated will return an error string
   */
  error?: string;
  /**
   * Whether the message is spam or not
   */
  isSpam?: boolean;
  /**
   * Spam rules triggered
   */
  rules?: Rule[];
  /**
   * Total spam score based on triggered rules
   */
  score?: number;
}
