// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * An address such as "Barry Gibbs <bg@example.com>" is represented
 * as Address{Name: "Barry Gibbs", Address: "bg@example.com"}.
 */
export interface Address {
  /**
   * Optional `string` value serialized in the `Address` wire field.
   */
  address?: string;
  /**
   * Optional `string` value serialized in the `Name` wire field.
   */
  name?: string;
}
