// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Trigger for Chaos
 */
export interface ChaosTrigger {
  /**
   * SMTP error code to return. The value must range from 400 to 599.
   */
  errorCode: number;
  /**
   * Probability (chance) of triggering the error. The value must range from 0 to 100.
   */
  probability: number;
}

/**
 * Triggers for the Chaos configuration
 */
export interface ChaosTriggers {
  /**
   * Trigger for Chaos
   */
  authentication?: ChaosTrigger;
  /**
   * Trigger for Chaos
   */
  recipient?: ChaosTrigger;
  /**
   * Trigger for Chaos
   */
  sender?: ChaosTrigger;
}
