// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../helpers/mock-sdk.mjs";
import { configureClient } from "../../dist/client.js";
import { SdkHttpError } from "../../dist/errors.js";
import {
  getMessageParams,
  getHeadersParams,
  attachmentParams,
  thumbnailParams,
  downloadRawParams,
  releaseMessageParams,
  sendMessageParams,
} from "../../dist/methods/message.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  getMessageParams: {
    route: "GetMessageParams",
    mediaType: null,
    invoke: (bag) => getMessageParams(config, { id: bag["ID"] }),
  },
  getHeadersParams: {
    route: "GetHeadersParams",
    mediaType: null,
    invoke: (bag) => getHeadersParams(config, { id: bag["ID"] }),
  },
  attachmentParams: {
    route: "AttachmentParams",
    mediaType: null,
    invoke: (bag) => attachmentParams(config, { id: bag["ID"], partId: bag["PartID"] }),
  },
  thumbnailParams: {
    route: "ThumbnailParams",
    mediaType: null,
    invoke: (bag) => thumbnailParams(config, { id: bag["ID"], partId: bag["PartID"] }),
  },
  downloadRawParams: {
    route: "DownloadRawParams",
    mediaType: null,
    invoke: (bag) => downloadRawParams(config, { id: bag["ID"] }),
  },
  releaseMessageParams: {
    route: "ReleaseMessageParams",
    mediaType: "application/json",
    invoke: (bag) => releaseMessageParams(config, { to: bag.__body?.["To"], id: bag["ID"] }),
  },
  sendMessageParams: {
    route: "SendMessageParams",
    mediaType: "application/json",
    invoke: (bag) =>
      sendMessageParams(config, {
        from: bag.__body?.["From"],
        attachments: bag.__body?.["Attachments"],
        bcc: bag.__body?.["Bcc"],
        cc: bag.__body?.["Cc"],
        html: bag.__body?.["HTML"],
        headers: bag.__body?.["Headers"],
        replyTo: bag.__body?.["ReplyTo"],
        subject: bag.__body?.["Subject"],
        tags: bag.__body?.["Tags"],
        text: bag.__body?.["Text"],
        to: bag.__body?.["To"],
      }),
  },
};

test("message methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
