// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../helpers/mock-sdk.mjs";
import { configureClient } from "../../dist/client.js";
import { SdkHttpError } from "../../dist/errors.js";
import {
  getMessagesParams,
  setReadStatusParams,
  deleteMessagesParams,
  searchParams,
  deleteSearchParams,
} from "../../dist/methods/messages.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  getMessagesParams: {
    route: "GetMessagesParams",
    mediaType: null,
    invoke: (bag) => getMessagesParams(config, { start: bag["start"], limit: bag["limit"] }),
  },
  setReadStatusParams: {
    route: "SetReadStatusParams",
    mediaType: "application/json",
    invoke: (bag) =>
      setReadStatusParams(config, {
        ids: bag.__body?.["IDs"],
        read: bag.__body?.["Read"],
        search: bag.__body?.["Search"],
        tz: bag["tz"],
      }),
  },
  deleteMessagesParams: {
    route: "DeleteMessagesParams",
    mediaType: "application/json",
    invoke: (bag) => deleteMessagesParams(config, { ids: bag.__body?.["IDs"] }),
  },
  searchParams: {
    route: "SearchParams",
    mediaType: null,
    invoke: (bag) =>
      searchParams(config, {
        query: bag["query"],
        start: bag["start"],
        limit: bag["limit"],
        tz: bag["tz"],
      }),
  },
  deleteSearchParams: {
    route: "DeleteSearchParams",
    mediaType: null,
    invoke: (bag) => deleteSearchParams(config, { query: bag["query"], tz: bag["tz"] }),
  },
};

test("messages methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
