// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ClientConfig, LoggingConfig } from "./client";
import { TestingNamespace } from "./methods/testing";
import { ApplicationNamespace } from "./methods/application";
import { MessageNamespace } from "./methods/message";
import { OtherNamespace } from "./methods/other";
import { MessagesNamespace } from "./methods/messages";
import { TagsNamespace } from "./methods/tags";

export class Mailpit {
  private readonly _config: ClientConfig;
  readonly testing: TestingNamespace;
  readonly application: ApplicationNamespace;
  readonly message: MessageNamespace;
  readonly other: OtherNamespace;
  readonly messages: MessagesNamespace;
  readonly tags: TagsNamespace;

  constructor(config: ClientConfig) {
    this._config = config;
    this.testing = new TestingNamespace(config);
    this.application = new ApplicationNamespace(config);
    this.message = new MessageNamespace(config);
    this.other = new OtherNamespace(config);
    this.messages = new MessagesNamespace(config);
    this.tags = new TagsNamespace(config);
  }

  /**
   * Turns SDK logging on and configures it. Logging is OFF by default — this
   * SDK reports nothing until you call this (or construct the client with
   * `logging: { enabled: true }`). Reports go to the endpoint this build was
   * generated with, or to the `endpoint` you pass; with neither, nothing is sent.
   * Pass `{ enabled: false }` to turn it off.
   */
  setLoggingConfig(config: LoggingConfig): void {
    this._config.logging = { ...this._config.logging, enabled: true, ...config };
  }
}
