// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type * as Types from "./types";
import { fromWire, toWire } from "./client";
import { SdkValidationError } from "./errors";

import { validateDateTime } from "./validation";

type RuntimeRecord = Record<string, unknown>;

interface RuntimeSchema {
  ref?: string;
  type?: string | readonly string[];
  nullable?: boolean;
  enum?: readonly unknown[];
  required?: readonly string[];
  properties?: Readonly<Record<string, RuntimeSchema>>;
  items?: RuntimeSchema;
  additionalProperties?: RuntimeSchema;
  oneOf?: readonly RuntimeSchema[];
  anyOf?: readonly RuntimeSchema[];
  allOf?: readonly RuntimeSchema[];
  minimum?: number;
  maximum?: number;
  exclusiveMinimum?: number | boolean;
  exclusiveMaximum?: number | boolean;
  multipleOf?: number;
  minLength?: number;
  maxLength?: number;
  minItems?: number;
  maxItems?: number;
  pattern?: string;
  format?: "email" | "uri" | "uuid" | "date" | "date-time";
}

const modelSchemas: Readonly<Record<string, RuntimeSchema>> = {
  ChaosTrigger: {
    type: "object",
    required: ["errorCode", "probability"],
    properties: { errorCode: { type: "integer" }, probability: { type: "integer" } },
  },
  ChaosTriggers: {
    type: "object",
    properties: {
      authentication: { ref: "ChaosTrigger" },
      recipient: { ref: "ChaosTrigger" },
      sender: { ref: "ChaosTrigger" },
    },
  },
  Message: {
    type: "object",
    properties: {
      attachments: { type: "array", items: { ref: "Attachment" } },
      bcc: { type: "array", items: { ref: "Address" } },
      cc: { type: "array", items: { ref: "Address" } },
      date: { type: "string", format: "date-time" },
      from: { ref: "Address" },
      html: { type: "string" },
      id: { type: "string" },
      inline: { type: "array", items: { ref: "Attachment" } },
      listUnsubscribe: { ref: "ListUnsubscribe" },
      messageId: { type: "string" },
      replyTo: { type: "array", items: { ref: "Address" } },
      returnPath: { type: "string" },
      size: { type: "integer" },
      subject: { type: "string" },
      tags: { type: "array", items: { type: "string" } },
      text: { type: "string" },
      to: { type: "array", items: { ref: "Address" } },
      username: { type: "string" },
    },
  },
  MessageSummary: {
    type: "object",
    properties: {
      attachments: { type: "integer" },
      bcc: { type: "array", items: { ref: "Address" } },
      cc: { type: "array", items: { ref: "Address" } },
      created: { type: "string", format: "date-time" },
      from: { ref: "Address" },
      id: { type: "string" },
      messageId: { type: "string" },
      read: { type: "boolean" },
      replyTo: { type: "array", items: { ref: "Address" } },
      size: { type: "integer" },
      snippet: { type: "string" },
      subject: { type: "string" },
      tags: { type: "array", items: { type: "string" } },
      to: { type: "array", items: { ref: "Address" } },
      username: { type: "string" },
    },
  },
  MessagesSummary: {
    type: "object",
    properties: {
      messages: { type: "array", items: { ref: "MessageSummary" } },
      messagesCount: { type: "integer" },
      messagesUnread: { type: "integer" },
      start: { type: "integer" },
      tags: { type: "array", items: { type: "string" } },
      total: { type: "integer" },
      unread: { type: "integer" },
    },
  },
};

const isRecord = (value: unknown): value is RuntimeRecord =>
  value !== null && typeof value === "object" && !Array.isArray(value);

const childField = (field: string, property: string): string =>
  field ? `${field}.${property}` : property;

const hasType = (schema: RuntimeSchema, type: string): boolean =>
  schema.type === type || (Array.isArray(schema.type) && schema.type.includes(type));

const allowsNull = (schema: RuntimeSchema | undefined, seen = new Set<string>()): boolean => {
  if (!schema) return false;
  if (schema.nullable === true || hasType(schema, "null")) return true;
  if (!schema.ref || seen.has(schema.ref)) return false;
  seen.add(schema.ref);
  const referenced = modelSchemas[schema.ref];
  return referenced ? allowsNull(referenced, seen) : false;
};

const validationFailure = (field: string, code: "required", message: string): never => {
  throw new SdkValidationError(field, code, message);
};

const validateNode = (value: unknown, schema: RuntimeSchema, field: string): unknown => {
  if (schema.ref) {
    const referenced = modelSchemas[schema.ref];
    return referenced ? validateNode(value, referenced, field) : value;
  }

  if (value === null) {
    if (schema.nullable === true || hasType(schema, "null")) return value;
    return value;
  }

  if (schema.allOf) {
    for (const member of schema.allOf) validateNode(value, member, field);
  }

  if (schema.oneOf || schema.anyOf) {
    const members = schema.oneOf ?? schema.anyOf ?? [];
    let firstError: unknown;
    for (const member of members) {
      try {
        return validateNode(value, member, field);
      } catch (error) {
        firstError ??= error;
      }
    }
    if (firstError instanceof Error) throw firstError;
  }

  if (hasType(schema, "object") || schema.properties) {
    if (!isRecord(value)) return value;
    for (const property of schema.required ?? []) {
      const propertyValue = value[property];
      const propertySchema = schema.properties?.[property];
      const missing =
        !Object.prototype.hasOwnProperty.call(value, property) || propertyValue === undefined;
      const invalidNull = propertyValue === null && !allowsNull(propertySchema);
      if (missing || invalidNull) {
        validationFailure(
          childField(field, property),
          "required",
          `Validation failed for '${childField(field, property)}': value is required`,
        );
      }
    }
    for (const [property, propertySchema] of Object.entries(schema.properties ?? {})) {
      if (Object.prototype.hasOwnProperty.call(value, property)) {
        validateNode(value[property], propertySchema, childField(field, property));
      }
    }
    if (schema.additionalProperties) {
      for (const [property, propertyValue] of Object.entries(value)) {
        if (!(property in (schema.properties ?? {}))) {
          validateNode(propertyValue, schema.additionalProperties, childField(field, property));
        }
      }
    }
  }

  if (hasType(schema, "array")) {
    if (!Array.isArray(value)) return value;
    if (schema.items) {
      value.forEach((item, index) =>
        validateNode(item, schema.items as RuntimeSchema, childField(field, String(index))),
      );
    }
  }

  if (schema.format === "date-time") validateDateTime(field, value as string);

  return value;
};

const validateModel = <T>(value: T, typeName: string): T => {
  const schema = modelSchemas[typeName];
  return schema ? (validateNode(value, schema, "") as T) : value;
};

export const modelConstructionStyle = "typed-record" as const;

/** Constructs a validated Address model value. */
export function createAddress(value: Types.Address): Types.Address {
  return validateModel({ ...value }, "Address");
}

/** Constructs a validated AppInformation model value. */
export function createAppInformation(value: Types.AppInformation): Types.AppInformation {
  return validateModel({ ...value }, "AppInformation");
}

/** Constructs a validated Attachment model value. */
export function createAttachment(value: Types.Attachment): Types.Attachment {
  return validateModel({ ...value }, "Attachment");
}

/** Constructs a validated ChaosTrigger model value. */
export function createChaosTrigger(value: Types.ChaosTrigger): Types.ChaosTrigger {
  return validateModel({ ...value }, "ChaosTrigger");
}

/** Constructs a validated ChaosTriggers model value. */
export function createChaosTriggers(value: Types.ChaosTriggers): Types.ChaosTriggers {
  return validateModel({ ...value }, "ChaosTriggers");
}

/** Constructs a validated HTMLCheckResponse model value. */
export function createHTMLCheckResponse(value: Types.HTMLCheckResponse): Types.HTMLCheckResponse {
  return validateModel({ ...value }, "HTMLCheckResponse");
}

/** Constructs a validated HTMLCheckResult model value. */
export function createHTMLCheckResult(value: Types.HTMLCheckResult): Types.HTMLCheckResult {
  return validateModel({ ...value }, "HTMLCheckResult");
}

/** Constructs a validated HTMLCheckScore model value. */
export function createHTMLCheckScore(value: Types.HTMLCheckScore): Types.HTMLCheckScore {
  return validateModel({ ...value }, "HTMLCheckScore");
}

/** Constructs a validated HTMLCheckTotal model value. */
export function createHTMLCheckTotal(value: Types.HTMLCheckTotal): Types.HTMLCheckTotal {
  return validateModel({ ...value }, "HTMLCheckTotal");
}

/** Constructs a validated HTMLCheckWarning model value. */
export function createHTMLCheckWarning(value: Types.HTMLCheckWarning): Types.HTMLCheckWarning {
  return validateModel({ ...value }, "HTMLCheckWarning");
}

/** Constructs a validated Link model value. */
export function createLink(value: Types.Link): Types.Link {
  return validateModel({ ...value }, "Link");
}

/** Constructs a validated LinkCheckResponse model value. */
export function createLinkCheckResponse(value: Types.LinkCheckResponse): Types.LinkCheckResponse {
  return validateModel({ ...value }, "LinkCheckResponse");
}

/** Constructs a validated ListUnsubscribe model value. */
export function createListUnsubscribe(value: Types.ListUnsubscribe): Types.ListUnsubscribe {
  return validateModel({ ...value }, "ListUnsubscribe");
}

/** Constructs a validated Message model value. */
export function createMessage(value: Types.Message): Types.Message {
  return validateModel({ ...value }, "Message");
}

/** Constructs a validated MessageSummary model value. */
export function createMessageSummary(value: Types.MessageSummary): Types.MessageSummary {
  return validateModel({ ...value }, "MessageSummary");
}

/** Constructs a validated MessagesSummary model value. */
export function createMessagesSummary(value: Types.MessagesSummary): Types.MessagesSummary {
  return validateModel({ ...value }, "MessagesSummary");
}

/** Constructs a validated Rule model value. */
export function createRule(value: Types.Rule): Types.Rule {
  return validateModel({ ...value }, "Rule");
}

/** Constructs a validated SpamAssassinResponse model value. */
export function createSpamAssassinResponse(
  value: Types.SpamAssassinResponse,
): Types.SpamAssassinResponse {
  return validateModel({ ...value }, "SpamAssassinResponse");
}

/** Constructs a validated WebUIConfiguration model value. */
export function createWebUIConfiguration(
  value: Types.WebUIConfiguration,
): Types.WebUIConfiguration {
  return validateModel({ ...value }, "WebUIConfiguration");
}

/** Serializes a constructed model using the generated wire-name mapping. */
export function serializeModel<T>(value: T, typeName: string): unknown {
  return toWire(validateModel(value, typeName), typeName);
}

/** Decodes and validates a wire model through the generated public surface. */
export function deserializeModel<T>(value: unknown, typeName: string): T {
  return validateModel<T>(fromWire(value, typeName) as T, typeName);
}
