// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { WireSchema } from "./client";

/**
 * Wire-format field maps: idiomatic SDK property name → { wire: <JSON key> }
 * (with `type` for nested models, `fields` for inline object properties).
 * Consumed by `toWire`/`fromWire` in `./client` to translate request and
 * response payloads. One entry per model whose JSON keys differ from their
 * idiomatic SDK names, or that nests one.
 */
export const wireSchemas: Record<string, WireSchema> = {
  Address: {
    address: { wire: "Address" },
    name: { wire: "Name" },
  },
  AppInformation: {
    database: { wire: "Database" },
    databaseSize: { wire: "DatabaseSize" },
    latestVersion: { wire: "LatestVersion" },
    messages: { wire: "Messages" },
    runtimeStats: {
      wire: "RuntimeStats",
      fields: {
        memory: { wire: "Memory" },
        messagesDeleted: { wire: "MessagesDeleted" },
        smtpAccepted: { wire: "SMTPAccepted" },
        smtpAcceptedSize: { wire: "SMTPAcceptedSize" },
        smtpIgnored: { wire: "SMTPIgnored" },
        smtpRejected: { wire: "SMTPRejected" },
        uptime: { wire: "Uptime" },
      },
    },
    tags: { wire: "Tags" },
    unread: { wire: "Unread" },
    version: { wire: "Version" },
  },
  Attachment: {
    checksums: {
      wire: "Checksums",
      fields: { md5: { wire: "MD5" }, sha1: { wire: "SHA1" }, sha256: { wire: "SHA256" } },
    },
    contentId: { wire: "ContentID" },
    contentType: { wire: "ContentType" },
    fileName: { wire: "FileName" },
    partId: { wire: "PartID" },
    size: { wire: "Size" },
  },
  ChaosTrigger: {
    errorCode: { wire: "ErrorCode" },
    probability: { wire: "Probability" },
  },
  ChaosTriggers: {
    authentication: { wire: "Authentication", type: "ChaosTrigger" },
    recipient: { wire: "Recipient", type: "ChaosTrigger" },
    sender: { wire: "Sender", type: "ChaosTrigger" },
  },
  HTMLCheckResponse: {
    platforms: { wire: "Platforms" },
    total: { wire: "Total", type: "HTMLCheckTotal" },
    warnings: { wire: "Warnings", type: "HTMLCheckWarning" },
  },
  HTMLCheckResult: {
    family: { wire: "Family" },
    name: { wire: "Name" },
    noteNumber: { wire: "NoteNumber" },
    platform: { wire: "Platform" },
    support: { wire: "Support" },
    version: { wire: "Version" },
  },
  HTMLCheckScore: {
    found: { wire: "Found" },
    partial: { wire: "Partial" },
    supported: { wire: "Supported" },
    unsupported: { wire: "Unsupported" },
  },
  HTMLCheckTotal: {
    nodes: { wire: "Nodes" },
    partial: { wire: "Partial" },
    supported: { wire: "Supported" },
    tests: { wire: "Tests" },
    unsupported: { wire: "Unsupported" },
  },
  HTMLCheckWarning: {
    category: { wire: "Category" },
    description: { wire: "Description" },
    keywords: { wire: "Keywords" },
    notesByNumber: { wire: "NotesByNumber" },
    results: { wire: "Results", type: "HTMLCheckResult" },
    score: { wire: "Score", type: "HTMLCheckScore" },
    slug: { wire: "Slug" },
    tags: { wire: "Tags" },
    title: { wire: "Title" },
    url: { wire: "URL" },
  },
  Link: {
    status: { wire: "Status" },
    statusCode: { wire: "StatusCode" },
    url: { wire: "URL" },
  },
  LinkCheckResponse: {
    errors: { wire: "Errors" },
    links: { wire: "Links", type: "Link" },
  },
  ListUnsubscribe: {
    errors: { wire: "Errors" },
    header: { wire: "Header" },
    headerPost: { wire: "HeaderPost" },
    links: { wire: "Links" },
  },
  Message: {
    attachments: { wire: "Attachments", type: "Attachment" },
    bcc: { wire: "Bcc", type: "Address" },
    cc: { wire: "Cc", type: "Address" },
    date: { wire: "Date" },
    from: { wire: "From", type: "Address" },
    html: { wire: "HTML" },
    id: { wire: "ID" },
    inline: { wire: "Inline", type: "Attachment" },
    listUnsubscribe: { wire: "ListUnsubscribe", type: "ListUnsubscribe" },
    messageId: { wire: "MessageID" },
    replyTo: { wire: "ReplyTo", type: "Address" },
    returnPath: { wire: "ReturnPath" },
    size: { wire: "Size" },
    subject: { wire: "Subject" },
    tags: { wire: "Tags" },
    text: { wire: "Text" },
    to: { wire: "To", type: "Address" },
    username: { wire: "Username" },
  },
  MessageSummary: {
    attachments: { wire: "Attachments" },
    bcc: { wire: "Bcc", type: "Address" },
    cc: { wire: "Cc", type: "Address" },
    created: { wire: "Created" },
    from: { wire: "From", type: "Address" },
    id: { wire: "ID" },
    messageId: { wire: "MessageID" },
    read: { wire: "Read" },
    replyTo: { wire: "ReplyTo", type: "Address" },
    size: { wire: "Size" },
    snippet: { wire: "Snippet" },
    subject: { wire: "Subject" },
    tags: { wire: "Tags" },
    to: { wire: "To", type: "Address" },
    username: { wire: "Username" },
  },
  MessagesSummary: {
    messages: { wire: "messages", type: "MessageSummary" },
    messagesCount: { wire: "messages_count" },
    messagesUnread: { wire: "messages_unread" },
    start: { wire: "start" },
    tags: { wire: "tags" },
    total: { wire: "total" },
    unread: { wire: "unread" },
  },
  Rule: {
    description: { wire: "Description" },
    name: { wire: "Name" },
    score: { wire: "Score" },
  },
  SpamAssassinResponse: {
    error: { wire: "Error" },
    isSpam: { wire: "IsSpam" },
    rules: { wire: "Rules", type: "Rule" },
    score: { wire: "Score" },
  },
  WebUIConfiguration: {
    chaosEnabled: { wire: "ChaosEnabled" },
    duplicatesIgnored: { wire: "DuplicatesIgnored" },
    hideDeleteAllButton: { wire: "HideDeleteAllButton" },
    label: { wire: "Label" },
    messageRelay: {
      wire: "MessageRelay",
      fields: {
        allowedRecipients: { wire: "AllowedRecipients" },
        blockedRecipients: { wire: "BlockedRecipients" },
        enabled: { wire: "Enabled" },
        overrideFrom: { wire: "OverrideFrom" },
        preserveMessageIds: { wire: "PreserveMessageIDs" },
        returnPath: { wire: "ReturnPath" },
        smtpServer: { wire: "SMTPServer" },
      },
    },
    spamAssassin: { wire: "SpamAssassin" },
  },
};
